version: "3.9"


services:
    pg:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: a247996346A!
            POSTGRES_DB: vwr
            LANG: en_US.utf8
            LC_ALL: en_US.utf8
        ports:
        - "5433:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
        - pgdata:/var/lib/postgresql/data
        - ./initdb:/docker-entrypoint-initdb.d:ro


    redis:
        image: redis:7
        restart: unless-stopped
        ports:
        - "6379:6379"


    anvil:
        image: ghcr.io/foundry-rs/foundry:latest
        command: anvil -p 8545 --block-time 1
        ports:
        - "8545:8545"
        restart: unless-stopped

volumes:
    pgdata: